#!/bin/bash
# run-agent-sandbox.sh — per-agent sandbox lifecycle, runs ON the RHEL box.
#
# Re-derived from a development harness (bin/run-claude-agent) for the broker-centric model.
# The core re-derivation: secret injection is restricted to runner keys ONLY
# (CLAUDE_CODE_OAUTH_TOKEN / ANTHROPIC_API_KEY).  Connector creds (TELEGRAM_*,
# ALPACA_*, TAVILY_*, etc.) are NEVER injected — those live in the broker's
# secret store.  The OpenShell network policy (generated by openshell_policy.py)
# enforces the same invariant at the OS layer: the sandbox can reach only the
# co-placed broker endpoint + api.anthropic.com:443.
#
# Key lessons from the development-harness reference (preserved):
#   - PATH=/usr/local/bin: RHEL login shells omit it; claude is a native ELF there.
#   - `openshell sandbox create … -- true </dev/null`: bare create blocks on stdin;
#     the `-- true </dev/null` keeps it non-interactive.
#   - No `--upload` flag on create; use `openshell sandbox upload` separately.
#   - `--no-tty` on exec: required for unattended runs.
#
# Usage:
#   run-agent-sandbox.sh <agent-name> <project-dir> <task-description> [options]
#
# Options:
#   --policy <file>      OpenShell policy YAML (default: auto-generate via openshell_policy.py)
#   --broker-port <port> Broker endpoint port for generated policy (default: 8080)
#   --max <n>            Max concurrent sandboxes (default: ceil(ncpu/2), min 1)
#   --timeout <secs>     Sandbox exec timeout (default: 600)
#   --no-sandbox         Run claude directly, without OpenShell (escape hatch; debug only)
#
# Runner-key file (default: ~/.runner-keys.env):
#   Written by the bootstrap when it fetches the per-agent secret from Secrets
#   Manager.  Contains ONLY: CLAUDE_CODE_OAUTH_TOKEN and/or ANTHROPIC_API_KEY.
#   Override location via CLAUDE_AGENT_KEYS_FILE env var.
set -uo pipefail

export PATH="/usr/local/bin:$PATH"  # RHEL: /usr/local/bin omitted from login shell PATH

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

usage() {
    cat <<'USAGE'
Usage: run-agent-sandbox.sh <agent-name> <project-dir> <task-description> [options]

Options:
  --policy <file>      OpenShell policy YAML (default: auto-generate)
  --broker-port <port> Broker port in generated policy (default: 8080)
  --max <n>            Max concurrent sandboxes (default: ceil(ncpu/2))
  --timeout <secs>     Sandbox exec timeout in seconds (default: 600)
  --no-sandbox         Skip OpenShell; run claude directly (debug only)
USAGE
}

[ $# -lt 3 ] && { usage; exit 1; }

AGENT_NAME="$1"; PROJECT_DIR="$2"; TASK_DESC="$3"; shift 3

POLICY=""; BROKER_PORT=8080; MAX=""; TIMEOUT=600; SANDBOX=true

while [ $# -gt 0 ]; do
    case "$1" in
        --policy)       POLICY="$2"; shift 2 ;;
        --broker-port)  BROKER_PORT="$2"; shift 2 ;;
        --max)          MAX="$2"; shift 2 ;;
        --timeout)      TIMEOUT="$2"; shift 2 ;;
        --no-sandbox)   SANDBOX=false; shift ;;
        *) echo "ERROR: unknown option: $1"; usage; exit 1 ;;
    esac
done

[ ! -d "$PROJECT_DIR" ] && {
    echo "ERROR: no such project directory: $PROJECT_DIR"; exit 1
}

# Concurrency cap: at most MAX sandboxes run at once; excess requests queue
# at the flock gate rather than saturating the box.  Default: ceil(ncpu/2).
# Override via --max flag or the CLAUDE_AGENT_MAX env var (from run-claude-agent).
if [ -z "$MAX" ]; then
    MAX="${CLAUDE_AGENT_MAX:-$(( ($(nproc) + 1) / 2 ))}"
    [ "$MAX" -lt 1 ] && MAX=1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TS=$(date +%Y%m%d-%H%M%S)
SESSION="agent-${AGENT_NAME}-${TS}"
_LOG_BASE="${CLAUDE_AGENT_LOG_DIR:-$HOME/claude-agents/logs}"
LOG_DIR="$_LOG_BASE/$SESSION"
mkdir -p "$LOG_DIR" "${CLAUDE_AGENT_LOG_DIR:-$HOME/claude-agents}/results"

# ---------------------------------------------------------------------------
# Policy generation (only when sandboxed + no explicit --policy given).
#
# Calls openshell_policy.py co-located with this script.  The generated
# policy whitelists ONLY the broker endpoint + api.anthropic.com; all
# connector hosts are absent.
# ---------------------------------------------------------------------------

if $SANDBOX; then
    command -v openshell >/dev/null 2>&1 \
        || { echo "ERROR: openshell not found — install it or use --no-sandbox"; exit 1; }

    if [ -z "$POLICY" ]; then
        POLICY="$LOG_DIR/policy-${AGENT_NAME}.yaml"
        python3 -c "
import importlib.util, sys
from pathlib import Path
spec = importlib.util.spec_from_file_location(
    'openshell_policy', Path('${SCRIPT_DIR}') / 'openshell_policy.py'
)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
params = mod.PolicyParams(agent_name='${AGENT_NAME}', broker_port=${BROKER_PORT})
Path('${POLICY}').write_text(mod.render_policy_yaml(params))
"
        echo "[sandbox] generated policy: $POLICY (broker port: $BROKER_PORT)"
    fi
fi

# ---------------------------------------------------------------------------
# Sandbox lifecycle script.
#
# Materialised into LOG_DIR/sandbox-run.sh and executed inside a tmux session.
# This separation mirrors the development-harness pattern: sandbox-run.sh holds the
# openshell commands; the tmux wrapper below holds the flock gate + logging.
#
# OpenShell v0.0.71 lifecycle (verified on box):
#   create … -- true </dev/null  — non-interactive keep-alive; bare create blocks
#   sandbox upload               — lands at /sandbox/project/<basename>
#   sandbox exec --no-tty …     — run claude -p with runner-key env vars only
#   sandbox delete               — on EXIT trap so cleanup runs even on failure
# ---------------------------------------------------------------------------

if $SANDBOX; then
    SBX="$LOG_DIR/sandbox-run.sh"
    {
        printf '#!/bin/bash\n'
        printf 'set -uo pipefail\n'
        printf 'export PATH="/usr/local/bin:$PATH"\n'
        printf 'export OPENSHELL_GATEWAY="${OPENSHELL_GATEWAY:-openshell}"\n'
        printf 'S=%q\n'             "$SESSION"
        printf 'POLICY=%q\n'        "$POLICY"
        printf 'PROJECT_DIR=%q\n'   "$PROJECT_DIR"
        printf 'EXEC_TIMEOUT=%q\n'  "$TIMEOUT"
        cat <<'SBXBODY'
TASK="$1"
DEST="/sandbox/project"
WORKDIR="$DEST/$(basename "$PROJECT_DIR")"
POL_ARG=(); [ -n "$POLICY" ] && POL_ARG=(--policy "$POLICY")

# Runner-key injection — allowlist enforced here at the bash level too.
# CLAUDE_CODE_OAUTH_TOKEN and ANTHROPIC_API_KEY are the only keys the
# claude harness needs.  Connector creds are NEVER in this list.
RUNNER_KEY_ALLOWLIST=("CLAUDE_CODE_OAUTH_TOKEN" "ANTHROPIC_API_KEY")
ENV_ARGS=()
_keys_file="${CLAUDE_AGENT_KEYS_FILE:-$HOME/.runner-keys.env}"
if [ -f "$_keys_file" ]; then
    set -a; . "$_keys_file"; set +a
fi
for _key in "${RUNNER_KEY_ALLOWLIST[@]}"; do
    [ -n "${!_key:-}" ] && ENV_ARGS+=(--env "$_key=${!_key}")
done

# Trap: delete sandbox on any exit (clean shutdown or error).
trap 'openshell sandbox delete "$S" >/dev/null 2>&1 || true' EXIT

echo "[sandbox] create $S"
openshell sandbox create --name "$S" "${POL_ARG[@]}" --auto-providers --no-tty \
    -- true </dev/null

echo "[sandbox] upload $PROJECT_DIR -> $DEST"
openshell sandbox upload "$S" "$PROJECT_DIR" "$DEST"

echo "[sandbox] exec claude in $WORKDIR"
openshell sandbox exec -n "$S" --workdir "$WORKDIR" --no-tty --timeout "$EXEC_TIMEOUT" \
    "${ENV_ARGS[@]}" -- claude -p "$TASK" </dev/null
SBXBODY
    } > "$SBX"
    chmod +x "$SBX"
    RUN_CMD="bash $SBX"
else
    # No-sandbox escape hatch: run claude directly (for local debugging only).
    RUN_CMD="claude -p"
fi

# ---------------------------------------------------------------------------
# tmux wrapper with flock concurrency gate.
#
# Holds one of MAX flock slots for the job's lifetime.  Excess runs park
# at the flock call ("queued") rather than overloading the box.  The slot
# is released when this wrapper's shell exits.
# ---------------------------------------------------------------------------

WRAPPER="$LOG_DIR/run.sh"
cat > "$WRAPPER" <<EOF
#!/bin/bash
TASK_FILE="\$1"; LOG_FILE="\$2"; RESULT_FILE="\$3"; EXIT_FILE="\$4"
RUN_CMD="\$5"; MAX="\${6:-$MAX}"
echo "======== Claude agent sandbox ========"
echo "Agent:   $AGENT_NAME"
echo "Session: $SESSION"
echo "Started: \$(date)"
echo "Task:    \$(cat "\$TASK_FILE")"

SLOT_DIR="\${CLAUDE_AGENT_LOG_DIR:-\$HOME/claude-agents}/slots"
mkdir -p "\$SLOT_DIR"; slot=0
while [ "\$slot" -eq 0 ]; do
    for i in \$(seq 1 "\$MAX"); do
        exec {SLOT_FD}>"\$SLOT_DIR/slot.\$i" || continue
        if flock -n "\$SLOT_FD"; then slot="\$i"; break; fi
        exec {SLOT_FD}>&-
    done
    [ "\$slot" -eq 0 ] && {
        echo "[\$(date)] all \$MAX run slots busy — queued, waiting..."
        sleep 5
    }
done
echo "[\$(date)] acquired slot \$slot/\$MAX — running."
echo "======================================="

\$RUN_CMD "\$(cat "\$TASK_FILE")" 2>&1 | tee "\$LOG_FILE" > "\$RESULT_FILE"
echo \${PIPESTATUS[0]} > "\$EXIT_FILE"
echo "Completed: \$(date)"
EOF
chmod +x "$WRAPPER"

echo "$TASK_DESC" > "$LOG_DIR/task.txt"

cat > "${CLAUDE_AGENT_LOG_DIR:-$HOME/claude-agents}/results/${SESSION}-info.txt" <<EOF
Agent:       $AGENT_NAME
Session:     $SESSION
Project:     $PROJECT_DIR
Policy:      ${POLICY:-<none>}
Sandbox:     $SANDBOX
Broker port: $BROKER_PORT
Concurrency: $MAX
Started:     $(date)
Logs:        $LOG_DIR/session.log
EOF

# Ensure tmux server is alive (can time out on long-lived idle boxes).
tmux start-server 2>/dev/null || true
tmux new-session -d -s "$SESSION" -c "$PROJECT_DIR" \
    "$WRAPPER" \
    "$LOG_DIR/task.txt" \
    "$LOG_DIR/session.log" \
    "$LOG_DIR/result.txt" \
    "$LOG_DIR/exit_code.txt" \
    "$RUN_CMD" \
    "$MAX"

if ! tmux has-session -t "$SESSION" 2>/dev/null; then
    echo "ERROR: launch failed — tmux session '$SESSION' not found; inspect $LOG_DIR/"
    exit 1
fi

echo "launched: $SESSION"
echo "  policy:      ${POLICY:-<none (no-sandbox)>}"
echo "  concurrency: $MAX"
echo "  logs:        tail -f $LOG_DIR/session.log"
echo "  attach:      tmux attach -t $SESSION"
